export interface InfoPartido {
  sigla: string;
  nomeCompleto: string;
  numeroTSE?: number;
  corPrimaria: string;
  corSecundaria: string;
  corTexto: string;
  corBorda: string;
  emojiBandeira: string;
}

export const PARTIDOS_INFO: Record<string, InfoPartido> = {
  PL: {
    sigla: 'PL',
    nomeCompleto: 'Partido Liberal',
    numeroTSE: 22,
    corPrimaria: '#1b355a',
    corSecundaria: '#f9c631',
    corTexto: '#ffffff',
    corBorda: '#2b4c7e',
    emojiBandeira: '🟦',
  },
  PT: {
    sigla: 'PT',
    nomeCompleto: 'Partido dos Trabalhadores',
    numeroTSE: 13,
    corPrimaria: '#b91c1c',
    corSecundaria: '#fca5a5',
    corTexto: '#ffffff',
    corBorda: '#dc2626',
    emojiBandeira: '🟥',
  },
  PSD: {
    sigla: 'PSD',
    nomeCompleto: 'Partido Social Democrático',
    numeroTSE: 55,
    corPrimaria: '#1e3a8a',
    corSecundaria: '#f59e0b',
    corTexto: '#ffffff',
    corBorda: '#3b82f6',
    emojiBandeira: '🟦',
  },
  REPUBLICANOS: {
    sigla: 'REPUBLICANOS',
    nomeCompleto: 'Republicanos',
    numeroTSE: 10,
    corPrimaria: '#0369a1',
    corSecundaria: '#10b981',
    corTexto: '#ffffff',
    corBorda: '#0284c7',
    emojiBandeira: '🔵',
  },
  'UNIÃO': {
    sigla: 'UNIÃO',
    nomeCompleto: 'União Brasil',
    numeroTSE: 44,
    corPrimaria: '#0284c7',
    corSecundaria: '#fbbf24',
    corTexto: '#ffffff',
    corBorda: '#38bdf8',
    emojiBandeira: '🔷',
  },
  UNIAO: {
    sigla: 'UNIAO',
    nomeCompleto: 'União Brasil',
    numeroTSE: 44,
    corPrimaria: '#0284c7',
    corSecundaria: '#fbbf24',
    corTexto: '#ffffff',
    corBorda: '#38bdf8',
    emojiBandeira: '🔷',
  },
  PP: {
    sigla: 'PP',
    nomeCompleto: 'Progressistas',
    numeroTSE: 11,
    corPrimaria: '#0f766e',
    corSecundaria: '#67e8f9',
    corTexto: '#ffffff',
    corBorda: '#14b8a6',
    emojiBandeira: '🟩',
  },
  MDB: {
    sigla: 'MDB',
    nomeCompleto: 'Movimento Democrático Brasileiro',
    numeroTSE: 15,
    corPrimaria: '#15803d',
    corSecundaria: '#ef4444',
    corTexto: '#ffffff',
    corBorda: '#22c55e',
    emojiBandeira: '🟢',
  },
  PSOL: {
    sigla: 'PSOL',
    nomeCompleto: 'Partido Socialismo e Liberdade',
    numeroTSE: 50,
    corPrimaria: '#d97706',
    corSecundaria: '#7c3aed',
    corTexto: '#ffffff',
    corBorda: '#f59e0b',
    emojiBandeira: '🟨',
  },
  PODE: {
    sigla: 'PODE',
    nomeCompleto: 'Podemos',
    numeroTSE: 20,
    corPrimaria: '#0d9488',
    corSecundaria: '#a7f3d0',
    corTexto: '#ffffff',
    corBorda: '#14b8a6',
    emojiBandeira: '🟢',
  },
  PSB: {
    sigla: 'PSB',
    nomeCompleto: 'Partido Socialista Brasileiro',
    numeroTSE: 40,
    corPrimaria: '#be123c',
    corSecundaria: '#facc15',
    corTexto: '#ffffff',
    corBorda: '#e11d48',
    emojiBandeira: '🔴',
  },
  PSDB: {
    sigla: 'PSDB',
    nomeCompleto: 'Partido da Social Democracia Brasileira',
    numeroTSE: 45,
    corPrimaria: '#1d4ed8',
    corSecundaria: '#fde047',
    corTexto: '#ffffff',
    corBorda: '#3b82f6',
    emojiBandeira: '🟦',
  },
  NOVO: {
    sigla: 'NOVO',
    nomeCompleto: 'Partido Novo',
    numeroTSE: 30,
    corPrimaria: '#c2410c',
    corSecundaria: '#fdba74',
    corTexto: '#ffffff',
    corBorda: '#ea580c',
    emojiBandeira: '🟧',
  },
  REDE: {
    sigla: 'REDE',
    nomeCompleto: 'Rede Sustentabilidade',
    numeroTSE: 18,
    corPrimaria: '#047857',
    corSecundaria: '#fb923c',
    corTexto: '#ffffff',
    corBorda: '#10b981',
    emojiBandeira: '🟩',
  },
  PCDOB: {
    sigla: 'PCDOB',
    nomeCompleto: 'Partido Comunista do Brasil',
    numeroTSE: 65,
    corPrimaria: '#991b1b',
    corSecundaria: '#fef08a',
    corTexto: '#ffffff',
    corBorda: '#dc2626',
    emojiBandeira: '🟥',
  },
  SOLIDARIEDADE: {
    sigla: 'SOLIDARIEDADE',
    nomeCompleto: 'Solidariedade',
    numeroTSE: 77,
    corPrimaria: '#ea580c',
    corSecundaria: '#fed7aa',
    corTexto: '#ffffff',
    corBorda: '#f97316',
    emojiBandeira: '🟧',
  },
  PRD: {
    sigla: 'PRD',
    nomeCompleto: 'Partido Renovação Democrática',
    numeroTSE: 25,
    corPrimaria: '#334155',
    corSecundaria: '#94a3b8',
    corTexto: '#ffffff',
    corBorda: '#475569',
    emojiBandeira: '⬛',
  },
  'MISSÃO': {
    sigla: 'MISSÃO',
    nomeCompleto: 'Missão',
    corPrimaria: '#0f172a',
    corSecundaria: '#cbd5e1',
    corTexto: '#ffffff',
    corBorda: '#334155',
    emojiBandeira: '⬛',
  },
};

export function obterInfoPartido(sigla: string | null | undefined): InfoPartido {
  if (!sigla) {
    return {
      sigla: 'S/P',
      nomeCompleto: 'Sem Partido',
      corPrimaria: '#475569',
      corSecundaria: '#94a3b8',
      corTexto: '#ffffff',
      corBorda: '#64748b',
      emojiBandeira: '⚪',
    };
  }
  const limpa = sigla.toUpperCase().trim();
  return PARTIDOS_INFO[limpa] ?? {
    sigla: limpa,
    nomeCompleto: limpa,
    corPrimaria: '#334155',
    corSecundaria: '#94a3b8',
    corTexto: '#ffffff',
    corBorda: '#475569',
    emojiBandeira: '🏛️',
  };
}
